import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ClipboardCheck, FileText, Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import DocumentAnalysisView from "@/components/DocumentAnalysisView";
import { apiGet, apiPost } from "@/lib/api";
import type { DocumentAnalysis, ModuleItem } from "@/lib/types";

export default function Assignments() {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [marks, setMarks] = useState<2 | 5 | 10>(5);
  const [assignment, setAssignment] = useState<DocumentAnalysis | null>(null);
  const documents = useQuery({ queryKey: ["module", "documents"], queryFn: () => apiGet<ModuleItem[]>("/modules/documents") });
  const pdfs = (documents.data ?? []).filter((document) => document.file_type === "application/pdf");
  useEffect(() => { if (!selectedId && pdfs[0]) setSelectedId(pdfs[0].id); }, [pdfs, selectedId]);
  const generate = useMutation({ mutationFn: () => apiPost<DocumentAnalysis>(`/modules/documents/${selectedId}/analyze`, { action: "assignment", marks }), onSuccess: (value) => { setAssignment(value); toast.success("Assignment generated"); }, onError: (error: Error) => toast.error(error.message) });
  return <div className="space-y-7" data-testid="assignments-page"><section className="border-b border-slate-200 pb-6"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-amber-600">Homework builder</p><h1 className="font-heading text-4xl font-semibold tracking-[-0.05em] text-slate-900">Assignments</h1><p className="mt-2 text-sm text-slate-500">Choose an uploaded PDF and create clear homework with a marking guide.</p></section>{pdfs.length ? <div className="grid gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><Card className="border-slate-200 bg-white p-3 shadow-sm"><p className="px-2 py-2 text-sm font-semibold text-slate-800">Uploaded PDFs</p>{pdfs.map((pdf) => <button key={pdf.id} data-testid={`assignment-document-${pdf.id}`} onClick={() => { setSelectedId(pdf.id); setAssignment(null); }} className={`mt-1 flex w-full items-center gap-3 rounded-xl p-3 text-left ${selectedId === pdf.id ? "bg-amber-50 ring-1 ring-amber-100" : "hover:bg-slate-50"}`}><FileText className="size-4 text-amber-600" /><span className="truncate text-xs font-semibold text-slate-700">{pdf.title}</span></button>)}</Card><div className="space-y-5"><Card className="border-amber-100 bg-gradient-to-r from-amber-50 to-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-amber-700">Marks per question</p><div className="mt-3 flex gap-2">{([2, 5, 10] as const).map((value) => <button key={value} data-testid={`assignment-marks-${value}`} onClick={() => setMarks(value)} className={`rounded-xl px-4 py-2 text-xs font-bold ${marks === value ? "bg-amber-500 text-white" : "bg-white text-amber-700 ring-1 ring-amber-200"}`}>{value} marks</button>)}</div><Button data-testid="assignment-generate-button" disabled={!selectedId || generate.isPending} onClick={() => generate.mutate()} className="mt-5 bg-amber-500 text-white hover:bg-amber-600">{generate.isPending ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}Generate assignment</Button></Card><Card className="min-h-80 border-slate-200 bg-white p-6 shadow-sm" data-testid="assignment-result">{generate.isPending ? <div className="grid min-h-64 place-items-center"><Loader2 className="size-7 animate-spin text-amber-500" /></div> : assignment ? <DocumentAnalysisView analysis={assignment} /> : <div className="grid min-h-64 place-items-center text-center"><div><ClipboardCheck className="mx-auto mb-3 size-8 text-amber-300" /><p className="text-sm font-semibold text-slate-700">Your generated homework will appear here</p></div></div>}</Card></div></div> : <Card className="border-dashed border-amber-200 bg-amber-50/60 p-12 text-center"><FileText className="mx-auto mb-3 size-8 text-amber-500" /><p className="text-sm font-semibold text-slate-700">Upload a PDF to create an assignment</p><Link to="/app/documents" data-testid="assignments-upload-link" className="mt-4 inline-block rounded-lg bg-amber-500 px-4 py-2 text-xs font-semibold text-white">Go to Documents</Link></Card>}</div>;
}