import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowUpRight, MessageSquare } from "lucide-react";
import { Card } from "@/components/ui/card";
import { apiGet } from "@/lib/api";
import type { ConversationSummary } from "@/lib/types";

export default function Conversations() {
  const query = useQuery({ queryKey: ["conversations"], queryFn: () => apiGet<ConversationSummary[]>("/conversations") });
  return <div className="space-y-8" data-testid="conversations-page"><section className="border-b border-white/10 pb-7"><p className="mb-3 font-mono text-[10px] uppercase tracking-[0.28em] text-[#4d8aff]">Archive / context</p><h1 className="text-4xl font-light tracking-[-0.05em]">Conversations</h1><p className="mt-3 text-sm text-zinc-500">Every prompt, source, provider, and fallback stays attached to its thread.</p></section><div className="space-y-2">{(query.data ?? []).map((conversation) => <Link key={conversation.id} to="/app/workspace" data-testid={`conversation-row-${conversation.id}`}><Card className="flex flex-row items-center justify-between border-white/10 bg-[#121212] p-5 hover:-translate-y-0.5 hover:border-white/20" data-testid={`conversation-card-${conversation.id}`}><div className="flex items-center gap-4"><div className="grid size-9 place-items-center rounded-md bg-[#0055ff]/10 text-[#6d9fff]"><MessageSquare className="size-4" /></div><div><p className="text-sm text-zinc-200">{conversation.title}</p><p className="mt-1 text-xs text-zinc-600">{conversation.message_count} messages · {conversation.provider_id ?? "router"}</p></div></div><ArrowUpRight className="size-4 text-zinc-600" /></Card></Link>)}{!query.data?.length && <Card className="border-white/10 bg-[#121212] p-16 text-center"><MessageSquare className="mx-auto mb-4 size-8 text-zinc-700" /><p className="text-sm text-zinc-400">No conversations yet.</p><Link to="/app/workspace" className="mt-4 inline-block text-xs text-[#6d9fff]" data-testid="conversations-empty-link">Open AI workspace</Link></Card>}</div></div>;
}