import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowUpRight, BrainCircuit, Clock3, Network, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiGet } from "@/lib/api";
import type { ConversationSummary, ProviderStatus } from "@/lib/types";

export default function Dashboard() {
  const conversations = useQuery({ queryKey: ["conversations"], queryFn: () => apiGet<ConversationSummary[]>("/conversations") });
  const providers = useQuery({ queryKey: ["providers"], queryFn: () => apiGet<ProviderStatus[]>("/providers") });
  const connected = providers.data?.filter((provider) => provider.configured).length ?? 0;
  return <div className="space-y-8" data-testid="dashboard-page">
    <section className="flex flex-col justify-between gap-6 border-b border-white/10 pb-8 md:flex-row md:items-end"><div><p className="mb-3 font-mono text-[10px] uppercase tracking-[0.28em] text-[#4d8aff]">System / 01</p><h1 className="text-4xl font-light tracking-[-0.05em] text-white sm:text-5xl" data-testid="dashboard-heading">Good to see you.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-zinc-500">Your intelligence layer is ready. Route a prompt, connect another provider, or return to an active thread.</p></div><Link to="/app/workspace" data-testid="dashboard-start-chat-link"><Button className="h-10 gap-2 bg-[#0055ff] text-white hover:bg-[#0044cc]">Open AI workspace <ArrowUpRight className="size-4" /></Button></Link></section>
    <div className="grid gap-px overflow-hidden rounded-lg border border-white/10 bg-white/10 md:grid-cols-3"><div className="bg-[#121212] p-6" data-testid="dashboard-stat-conversations"><div className="mb-8 flex items-center justify-between text-zinc-500"><span className="font-mono text-[10px] uppercase tracking-[0.18em]">Conversations</span><Clock3 className="size-4" /></div><p className="text-4xl font-light tracking-[-0.05em]">{conversations.data?.length ?? 0}</p><p className="mt-2 text-xs text-zinc-600">Persistent threads</p></div><div className="bg-[#121212] p-6" data-testid="dashboard-stat-providers"><div className="mb-8 flex items-center justify-between text-zinc-500"><span className="font-mono text-[10px] uppercase tracking-[0.18em]">Connected AI</span><Network className="size-4" /></div><p className="text-4xl font-light tracking-[-0.05em]">{connected}</p><p className="mt-2 text-xs text-zinc-600">Eligible routing nodes</p></div><div className="bg-[#121212] p-6" data-testid="dashboard-stat-fallback"><div className="mb-8 flex items-center justify-between text-zinc-500"><span className="font-mono text-[10px] uppercase tracking-[0.18em]">Fallback mode</span><ShieldCheck className="size-4" /></div><p className="text-4xl font-light tracking-[-0.05em]">ON</p><p className="mt-2 text-xs text-zinc-600">Safe before-stream switching</p></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><Card className="border-white/10 bg-[#121212]" data-testid="dashboard-recent-card"><CardHeader className="flex flex-row items-center justify-between border-b border-white/10 pb-5"><CardTitle className="font-mono text-xs uppercase tracking-[0.18em] text-zinc-300">Recent conversations</CardTitle><Link to="/app/conversations" className="text-xs text-[#6d9fff] hover:text-white" data-testid="dashboard-view-conversations-link">View all</Link></CardHeader><CardContent className="p-0">{(conversations.data ?? []).slice(0, 4).map((conversation) => <Link to="/app/workspace" key={conversation.id} data-testid={`dashboard-conversation-${conversation.id}`} className="flex items-center justify-between border-b border-white/5 px-6 py-4 hover:bg-white/[0.03]"><div><p className="text-sm text-zinc-200">{conversation.title}</p><p className="mt-1 text-xs text-zinc-600">{conversation.message_count} messages</p></div><ArrowUpRight className="size-4 text-zinc-600" /></Link>)}{!conversations.data?.length && <div className="p-10 text-center"><BrainCircuit className="mx-auto mb-3 size-7 text-zinc-700" /><p className="text-sm text-zinc-400">Your first thread starts here.</p><Link to="/app/workspace" className="mt-4 inline-flex text-xs text-[#6d9fff]" data-testid="dashboard-empty-start-link">Start a conversation <ArrowUpRight className="ml-1 size-3" /></Link></div>}</CardContent></Card><Card className="border-white/10 bg-[#121212]" data-testid="dashboard-setup-card"><CardHeader><CardTitle className="flex items-center gap-2 text-base font-normal"><Sparkles className="size-4 text-[#4d8aff]" />Finish your setup</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm leading-6 text-zinc-500">Choose your preferred providers. Statx will never claim a provider is connected until its authorization or server credential is valid.</p><div className="space-y-3">{(providers.data ?? []).slice(0, 4).map((provider) => <div key={provider.id} className="flex items-center justify-between border-b border-white/5 pb-3 text-sm"><span className="text-zinc-300">{provider.name}</span><Badge variant={provider.configured ? "default" : "outline"} className={provider.configured ? "bg-[#34c759]/15 text-[#6ee7a1]" : "text-zinc-600"}>{provider.configured ? "Ready" : "Needs setup"}</Badge></div>)}</div><Link to="/app/providers" data-testid="dashboard-manage-providers-link"><Button variant="outline" className="w-full border-white/10 bg-transparent text-zinc-300 hover:bg-white/5 hover:text-white"><Plus className="size-4" />Manage providers</Button></Link></CardContent></Card></div>
  </div>;
}