import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowUpRight, BrainCircuit, FileText, History as HistoryIcon, MessageSquare, Trophy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { apiGet } from "@/lib/api";
import type { ConversationSummary, ExamResult, ModuleItem } from "@/lib/types";

const statStyles = [
  { shell: "from-indigo-500 to-blue-600", soft: "bg-indigo-50 text-indigo-600" },
  { shell: "from-cyan-500 to-blue-500", soft: "bg-cyan-50 text-cyan-600" },
  { shell: "from-emerald-500 to-teal-500", soft: "bg-emerald-50 text-emerald-600" },
  { shell: "from-amber-400 to-orange-500", soft: "bg-amber-50 text-amber-600" },
];

export default function Dashboard() {
  const conversations = useQuery({ queryKey: ["conversations"], queryFn: () => apiGet<ConversationSummary[]>("/conversations") });
  const documents = useQuery({ queryKey: ["module", "documents"], queryFn: () => apiGet<ModuleItem[]>("/modules/documents") });
  const results = useQuery({ queryKey: ["exam-results"], queryFn: () => apiGet<ExamResult[]>("/modules/results/exams") });
  const stats = [
    { label: "Chat history", value: conversations.data?.length ?? 0, note: "Saved conversations", icon: MessageSquare, href: "/app/workspace" },
    { label: "Documents", value: documents.data?.length ?? 0, note: "Uploaded references", icon: FileText, href: "/app/documents" },
    { label: "History", value: documents.data?.length ?? 0, note: "Document timelines", icon: HistoryIcon, href: "/app/history" },
    { label: "Results", value: results.data?.length ?? 0, note: "Completed exams", icon: Trophy, href: "/app/results" },
  ];
  const recent = [
    ...(documents.data ?? []).map((item) => ({ ...item, section: "Document", href: "/app/documents", color: "bg-cyan-500" })),
    ...(results.data ?? []).map((item) => ({ id: item.id, title: `${item.document_title} — ${item.percentage}%`, updated_at: item.submitted_at, section: "Result", href: "/app/results", color: "bg-amber-500" })),
  ].sort((a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()).slice(0, 6);
  return <div className="space-y-8" data-testid="dashboard-page">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 via-blue-600 to-cyan-500 p-7 text-white shadow-xl shadow-indigo-200/60 sm:p-9"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-indigo-100">Your StatNex AI workspace</p><h1 className="font-heading text-4xl font-semibold tracking-[-0.05em] text-white sm:text-5xl" data-testid="dashboard-heading">Everything in one place.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-blue-50">Chat, add documents, revisit your history, create assignments, and track exam results.</p></div><Link to="/app/workspace" data-testid="dashboard-start-chat-link"><Button className="h-11 border border-white/30 bg-white text-indigo-700 shadow-sm hover:bg-indigo-50">Start a conversation <ArrowUpRight className="size-4" /></Button></Link></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat, index) => { const Icon = stat.icon; const style = statStyles[index]; return <Link to={stat.href} key={stat.label} data-testid={`dashboard-stat-${stat.label.toLowerCase().replaceAll(" ", "-")}`}><Card className="group relative overflow-hidden border-slate-200 bg-white p-5 shadow-sm hover:-translate-y-1 hover:shadow-lg"><div className={`absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${style.shell}`} /><div className={`mb-6 grid size-10 place-items-center rounded-xl ${style.soft}`}><Icon className="size-5" /></div><p className="text-3xl font-semibold tracking-tight text-slate-900">{stat.value}</p><p className="mt-1 text-sm font-medium text-slate-700">{stat.label}</p><p className="mt-1 text-xs text-slate-400">{stat.note}</p><ArrowUpRight className="absolute bottom-5 right-5 size-4 text-slate-300 group-hover:text-indigo-500" /></Card></Link>; })}</div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><Card className="border-slate-200 bg-white shadow-sm" data-testid="dashboard-activity-card"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="font-heading text-base font-semibold text-slate-900">Recent additions</p><p className="mt-1 text-xs text-slate-400">Documents and exam results</p></div></div><div className="divide-y divide-slate-100">{recent.map((item) => <Link to={item.href} key={`${item.section}-${item.id}`} className="flex items-center gap-4 px-6 py-4 hover:bg-slate-50" data-testid={`dashboard-activity-${item.id}`}><span className={`size-2.5 rounded-full ${item.color}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-700">{item.title}</p><p className="mt-0.5 text-xs text-slate-400">{item.section} · {new Date(item.updated_at).toLocaleDateString()}</p></div><ArrowUpRight className="size-4 text-slate-300" /></Link>)}{recent.length === 0 && <div className="px-6 py-14 text-center"><div className="mx-auto mb-4 grid size-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-500"><BrainCircuit className="size-6" /></div><p className="text-sm font-medium text-slate-700">Your workspace is ready</p><p className="mt-1 text-xs text-slate-400">Add a document or complete an exam to see it here.</p></div>}</div></Card><Card className="overflow-hidden border-slate-200 bg-gradient-to-br from-emerald-50 via-white to-cyan-50 p-6 shadow-sm" data-testid="dashboard-documents-card"><div className="mb-5 flex items-center justify-between"><div className="grid size-11 place-items-center rounded-2xl bg-gradient-to-br from-emerald-500 to-cyan-500 text-white shadow-md shadow-emerald-100"><FileText className="size-5" /></div><Link to="/app/history" className="text-xs font-medium text-emerald-700 hover:text-emerald-900" data-testid="dashboard-view-documents-link">Open history</Link></div><h2 className="font-heading text-xl font-semibold text-slate-900">Document history</h2><p className="mt-2 text-sm leading-6 text-slate-500">Your latest uploaded files and generated actions stay easy to revisit.</p><div className="mt-6 space-y-2">{(documents.data ?? []).slice(0, 3).map((document) => <div key={document.id} className="flex items-center gap-3 rounded-xl border border-emerald-100 bg-white/80 p-3"><FileText className="size-4 text-emerald-500" /><span className="min-w-0 flex-1 truncate text-xs font-medium text-slate-600">{document.title}</span></div>)}{!documents.data?.length && <Link to="/app/documents" className="block rounded-xl border border-dashed border-emerald-200 bg-white/60 p-4 text-center text-xs font-medium text-emerald-700" data-testid="dashboard-add-first-document-link">Add your first document</Link>}</div></Card></div>
  </div>;
}