import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { FileQuestion, FileText, Layers3, ListChecks, Loader2, NotebookPen, Send, Sparkles, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import DocumentAnalysisView from "@/components/DocumentAnalysisView";
import { apiGet, apiPost, apiPostForm } from "@/lib/api";
import type { DocumentAnalysis, ExamResult, ModuleItem } from "@/lib/types";

const actions = [
  { id: "summary", label: "Summarize", note: "Key ideas in a clear format", icon: FileText, style: "bg-blue-50 text-blue-600 border-blue-100" },
  { id: "notes", label: "Study notes", note: "Structured points and headings", icon: NotebookPen, style: "bg-cyan-50 text-cyan-600 border-cyan-100" },
  { id: "flashcards", label: "Flashcards", note: "Questions for quick revision", icon: Layers3, style: "bg-emerald-50 text-emerald-600 border-emerald-100" },
  { id: "mcqs", label: "Generate MCQs", note: "Practice with answer options", icon: ListChecks, style: "bg-amber-50 text-amber-600 border-amber-100" },
  { id: "descriptive", label: "Descriptive exam", note: "Written questions by marks", icon: FileQuestion, style: "bg-indigo-50 text-indigo-600 border-indigo-100" },
] as const;

export default function Documents() {
  const client = useQueryClient();
  const [searchParams] = useSearchParams();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [question, setQuestion] = useState("");
  const [result, setResult] = useState<DocumentAnalysis | null>(null);
  const [marks, setMarks] = useState<2 | 5 | 10>(5);
  const documents = useQuery({ queryKey: ["module", "documents"], queryFn: () => apiGet<ModuleItem[]>("/modules/documents") });
  useEffect(() => { const requested = searchParams.get("document"); if (!selectedId && documents.data?.length) setSelectedId(documents.data.find((item) => item.id === requested)?.id ?? documents.data[0].id); }, [documents.data, searchParams, selectedId]);
  const selected = documents.data?.find((document) => document.id === selectedId);
  const analyses = useQuery({ queryKey: ["document-analyses", selectedId], queryFn: () => apiGet<DocumentAnalysis[]>(`/modules/documents/${selectedId}/analyses`), enabled: Boolean(selectedId) });
  const upload = useMutation({ mutationFn: (files: File[]) => { const form = new FormData(); files.forEach((file) => form.append("files", file)); return apiPostForm<ModuleItem[]>("/modules/documents/upload", form); }, onSuccess: (items) => { setSelectedId(items[0]?.id ?? null); setResult(null); void client.invalidateQueries({ queryKey: ["module", "documents"] }); toast.success(`${items.length} document${items.length === 1 ? "" : "s"} added`); }, onError: (error: Error) => toast.error(error.message || "Upload failed") });
  const analyze = useMutation({ mutationFn: ({ action, prompt = "", questionMarks }: { action: DocumentAnalysis["action"]; prompt?: string; questionMarks?: 2 | 5 | 10 }) => apiPost<DocumentAnalysis>(`/modules/documents/${selectedId}/analyze`, { action, prompt, marks: questionMarks }), onSuccess: (analysis) => { if (analysis.action !== "ask") setResult(analysis); setQuestion(""); void client.invalidateQueries({ queryKey: ["document-analyses", selectedId] }); toast.success(analysis.action === "ask" ? "Answer ready" : "Generated with StatNex AI"); }, onError: (error: Error) => toast.error(error.message || "Generation failed") });
  const queueFiles = (files: File[]) => { if (files.length) upload.mutate(files); };
  const visibleResult = result ?? analyses.data?.find((analysis) => analysis.action !== "ask") ?? null;
  const saveResult = useMutation({ mutationFn: ({ correct, total }: { correct: number; total: number }) => apiPost<ExamResult>(`/modules/documents/${selectedId}/exam-results`, { analysis_id: visibleResult?.id, correct, total }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["exam-results"] }); toast.success("Result saved"); }, onError: (error: Error) => toast.error(error.message || "Could not save result") });
  const chatHistory = [...(analyses.data ?? [])].filter((analysis) => analysis.action === "ask").reverse();
  const documentActionPending = analyze.isPending && analyze.variables?.action !== "ask";
  const chatPending = analyze.isPending && analyze.variables?.action === "ask";
  return <div className="space-y-6" data-testid="documents-page">
    <section className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-6 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">Document intelligence</p><h1 className="font-heading text-4xl font-semibold tracking-[-0.05em] text-slate-900">Documents</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">Upload your material, then summarize it, build revision tools, or ask StatNex AI questions about it.</p></div><span className="rounded-full bg-cyan-50 px-3 py-1.5 text-xs font-semibold text-cyan-700">{documents.data?.length ?? 0} documents</span></section>
    <Card className="overflow-hidden border-blue-100 bg-gradient-to-r from-blue-50 via-white to-cyan-50 p-5 shadow-sm"><label data-testid="documents-upload-button" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); queueFiles(Array.from(event.dataTransfer.files)); }} className="group flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-blue-200 bg-white/75 p-5 text-center hover:border-blue-400 hover:bg-white"><div className="mb-3 grid size-11 place-items-center rounded-xl bg-gradient-to-br from-blue-600 to-cyan-500 text-white shadow-lg shadow-blue-200">{upload.isPending ? <Loader2 className="size-5 animate-spin" /> : <UploadCloud className="size-5" />}</div><p className="font-heading text-sm font-semibold text-slate-800">{upload.isPending ? "Adding your documents…" : "Drop documents here or browse"}</p><p className="mt-1 text-xs text-slate-500">PDF, DOCX, Markdown, CSV, or text · multiple files supported</p><input data-testid="documents-upload-input" className="sr-only" type="file" accept=".pdf,.docx,.md,.csv,.txt" multiple disabled={upload.isPending} onChange={(event) => { queueFiles(Array.from(event.target.files ?? [])); event.currentTarget.value = ""; }} /></label></Card>
    {(documents.data?.length ?? 0) > 0 && <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="space-y-5"><Card className="border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-blue-600">AI Action Workspace</p><h2 className="mt-1 truncate font-heading text-lg font-semibold text-slate-900">{selected?.title}</h2></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">Ready</span></div><div className="mb-4 flex flex-wrap items-center gap-2 rounded-xl bg-indigo-50 p-3"><span className="mr-1 text-xs font-semibold text-indigo-700">Question marks</span>{([2, 5, 10] as const).map((value) => <button key={value} data-testid={`document-marks-${value}`} onClick={() => setMarks(value)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${marks === value ? "bg-indigo-600 text-white shadow-sm" : "bg-white text-indigo-600 hover:bg-indigo-100"}`}>{value} marks</button>)}</div><div className="grid gap-3 sm:grid-cols-2">{actions.map(({ id, label, note, icon: Icon, style }) => <button key={id} data-testid={`document-action-${id}`} disabled={analyze.isPending} onClick={() => analyze.mutate({ action: id, questionMarks: id === "descriptive" ? marks : undefined })} className={`rounded-xl border p-4 text-left hover:-translate-y-0.5 hover:shadow-md disabled:opacity-60 ${style}`}><Icon className="mb-3 size-5" /><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-[11px] leading-4 opacity-75">{note}</p></button>)}</div></Card><Card className="min-h-80 border-slate-200 bg-white p-5 shadow-sm" data-testid="document-analysis-result">{documentActionPending ? <div className="grid min-h-72 place-items-center text-center"><div><Loader2 className="mx-auto mb-3 size-7 animate-spin text-blue-600" /><p className="font-heading text-base font-semibold text-slate-700">StatNex AI is creating your {analyze.variables?.action}…</p><p className="mt-1 text-xs text-slate-400">The finished result will stay linked to this document.</p></div></div> : visibleResult ? <DocumentAnalysisView analysis={visibleResult} onMcqComplete={(correct, total) => saveResult.mutate({ correct, total })} /> : <div className="grid min-h-72 place-items-center text-center"><div><Sparkles className="mx-auto mb-3 size-8 text-blue-300" /><p className="font-heading text-base font-semibold text-slate-600">Choose an AI action above</p><p className="mt-1 text-xs text-slate-400">Summaries, notes, flashcards, and questions appear here.</p></div></div>}</Card></div>
      <Card className="flex min-h-[560px] flex-col border-slate-200 bg-white shadow-sm" data-testid="document-chat-panel"><div className="border-b border-slate-100 p-5"><div className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-blue-600 text-white"><Sparkles className="size-5" /></div><h2 className="mt-4 font-heading text-lg font-semibold text-slate-900">Ask this document</h2><p className="mt-1 text-xs leading-5 text-slate-500">Answers stay grounded in the selected file.</p></div><div className="max-h-[520px] flex-1 space-y-4 overflow-y-auto p-4" data-testid="document-chat-messages">{chatHistory.length === 0 && !chatPending && <div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400">Try asking</p>{["Explain this in simple language", "What are the key takeaways?", "What should I revise first?"].map((suggestion) => <button key={suggestion} data-testid={`document-suggestion-${suggestion.toLowerCase().replaceAll(" ", "-").replaceAll("?", "")}`} onClick={() => analyze.mutate({ action: "ask", prompt: suggestion })} className="mt-2 block w-full rounded-xl bg-slate-50 p-3 text-left text-xs leading-5 text-slate-600 hover:bg-blue-50 hover:text-blue-700">{suggestion}</button>)}</div>}{chatHistory.map((message) => <div key={message.id} className="space-y-2" data-testid={`document-chat-message-${message.id}`}><div className="ml-7 rounded-2xl rounded-br-md bg-gradient-to-br from-indigo-500 to-blue-600 p-3 text-xs leading-5 text-white">{message.prompt}</div><div className="mr-5 rounded-2xl rounded-bl-md border border-blue-100 bg-blue-50 p-3 text-xs leading-6 text-slate-700"><span className="mb-1 block text-[9px] font-bold uppercase tracking-[0.14em] text-blue-600">StatNex AI</span>{message.content}</div></div>)}{chatPending && <div className="mr-5 rounded-2xl rounded-bl-md border border-blue-100 bg-blue-50 p-3 text-xs text-blue-700" data-testid="document-chat-loading"><Loader2 className="mr-2 inline size-3 animate-spin" />Thinking about your document…</div>}</div><div className="border-t border-slate-100 p-4"><Textarea data-testid="document-question-input" value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey && question.trim() && !analyze.isPending) { event.preventDefault(); analyze.mutate({ action: "ask", prompt: question }); } }} placeholder="Ask anything about this document" className="min-h-24 resize-none border-slate-200 bg-slate-50" /><Button data-testid="document-question-send" disabled={!question.trim() || analyze.isPending} onClick={() => analyze.mutate({ action: "ask", prompt: question })} className="mt-3 w-full bg-blue-600 text-white hover:bg-blue-700">{chatPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}Ask StatNex AI</Button></div></Card>
    </div>}
    {!documents.isLoading && !documents.data?.length && <Card className="border-dashed border-blue-200 bg-blue-50/50 p-12 text-center"><FileText className="mx-auto mb-3 size-7 text-blue-400" /><p className="text-sm font-semibold text-slate-700">Add a document to unlock the AI workspace</p></Card>}
  </div>;
}