import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowUpRight, Clock3, FileText, History as HistoryIcon, Sparkles, X } from "lucide-react";
import { Card } from "@/components/ui/card";
import DocumentAnalysisView from "@/components/DocumentAnalysisView";
import { apiGet } from "@/lib/api";
import type { DocumentAnalysis, ModuleItem } from "@/lib/types";

export default function History() {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [activeAnalysis, setActiveAnalysis] = useState<DocumentAnalysis | null>(null);
  const documents = useQuery({ queryKey: ["module", "documents"], queryFn: () => apiGet<ModuleItem[]>("/modules/documents") });
  useEffect(() => { if (!selectedId && documents.data?.[0]) setSelectedId(documents.data[0].id); }, [documents.data, selectedId]);
  const analyses = useQuery({ queryKey: ["document-analyses", selectedId], queryFn: () => apiGet<DocumentAnalysis[]>(`/modules/documents/${selectedId}/analyses`), enabled: Boolean(selectedId) });
  const selected = documents.data?.find((item) => item.id === selectedId);
  return <div className="space-y-7" data-testid="history-page">
    <section className="border-b border-slate-200 pb-6"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Document timeline</p><h1 className="font-heading text-4xl font-semibold tracking-[-0.05em] text-slate-900">History</h1><p className="mt-2 text-sm text-slate-500">Open any document, then click a saved summary, flashcard deck, exam, or answer to use it again.</p></section>
    <div className="grid gap-5 lg:grid-cols-[300px_minmax(0,1fr)]"><Card className="border-slate-200 bg-white p-3 shadow-sm"><div className="mb-3 flex items-center gap-2 px-2 py-1"><HistoryIcon className="size-4 text-cyan-600" /><p className="text-sm font-semibold text-slate-800">Uploaded documents</p></div><div className="space-y-1">{(documents.data ?? []).map((document) => <button key={document.id} data-testid={`history-document-${document.id}`} onClick={() => { setSelectedId(document.id); setActiveAnalysis(null); }} className={`w-full rounded-xl p-3 text-left ${selectedId === document.id ? "bg-cyan-50 ring-1 ring-cyan-100" : "hover:bg-slate-50"}`}><div className="flex gap-3"><div className="grid size-8 shrink-0 place-items-center rounded-lg bg-blue-50 text-blue-600"><FileText className="size-4" /></div><div className="min-w-0"><p className="truncate text-xs font-semibold text-slate-700">{document.title}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(document.updated_at).toLocaleDateString()}</p></div></div></button>)}{!documents.data?.length && <p className="p-5 text-center text-xs text-slate-400">No uploaded documents yet.</p>}</div></Card>
      <Card className="border-slate-200 bg-white p-6 shadow-sm" data-testid="history-timeline"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-600">Saved activity</p><h2 className="mt-1 font-heading text-xl font-semibold text-slate-900">{selected?.title ?? "Choose a document"}</h2></div>{selectedId && <Link to={`/app/documents?document=${selectedId}`} data-testid="history-open-document-button" className="inline-flex items-center gap-1 rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700 hover:bg-indigo-100">Open workspace<ArrowUpRight className="size-3" /></Link>}</div><div className="grid gap-3 sm:grid-cols-2">{(analyses.data ?? []).map((analysis, index) => <button key={analysis.id} onClick={() => setActiveAnalysis(analysis)} className="group flex gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 text-left hover:-translate-y-0.5 hover:border-cyan-200 hover:bg-cyan-50" data-testid={`history-action-${analysis.id}`}><div className={`grid size-9 shrink-0 place-items-center rounded-xl text-white ${index % 3 === 0 ? "bg-indigo-500" : index % 3 === 1 ? "bg-cyan-500" : "bg-emerald-500"}`}>{analysis.action === "ask" ? <Sparkles className="size-4" /> : <FileText className="size-4" />}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold capitalize text-slate-700">{analysis.action}</p><span className="flex items-center gap-1 text-[9px] text-slate-400"><Clock3 className="size-3" />{new Date(analysis.created_at).toLocaleDateString()}</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{analysis.prompt ?? analysis.content}</p><span className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-cyan-700">Open again<ArrowUpRight className="size-3" /></span></div></button>)}{selectedId && !analyses.isLoading && !analyses.data?.length && <div className="rounded-2xl border border-dashed border-cyan-200 bg-cyan-50/50 p-10 text-center sm:col-span-2"><Sparkles className="mx-auto mb-3 size-6 text-cyan-500" /><p className="text-sm font-medium text-slate-700">No AI history yet</p><p className="mt-1 text-xs text-slate-400">Open this document and choose an action.</p></div>}</div></Card></div>
    {activeAnalysis && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" data-testid="history-analysis-overlay" onMouseDown={(event) => { if (event.target === event.currentTarget) setActiveAnalysis(null); }}><div className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-slate-200 bg-white p-6 shadow-2xl" data-testid="history-analysis-detail"><div className="mb-6 flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-600">Saved {activeAnalysis.action}</p><h2 className="mt-1 font-heading text-xl font-semibold text-slate-900">{selected?.title}</h2></div><button data-testid="history-analysis-close" onClick={() => setActiveAnalysis(null)} className="grid size-9 place-items-center rounded-xl bg-slate-100 text-slate-500 hover:bg-slate-200"><X className="size-4" /></button></div><DocumentAnalysisView analysis={activeAnalysis} /><div className="mt-6 border-t border-slate-100 pt-5"><Link to={`/app/documents?document=${selectedId}`} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white" data-testid="history-analysis-workspace-link">Use in document workspace<ArrowUpRight className="size-4" /></Link></div></div></div>}
  </div>;
}