import { useQuery } from "@tanstack/react-query";
import { KeyRound, LockKeyhole, ServerCog } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiGet } from "@/lib/api";
import type { UserPublic } from "@/lib/types";

export default function Settings() {
  const me = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") });
  return <div className="space-y-8" data-testid="settings-page"><section className="border-b border-white/10 pb-7"><p className="mb-3 font-mono text-[10px] uppercase tracking-[0.28em] text-[#4d8aff]">System / preferences</p><h1 className="text-4xl font-light tracking-[-0.05em]">Settings</h1><p className="mt-3 text-sm text-zinc-500">Identity, security, and deployment boundaries for your Statx workspace.</p></section><div className="grid gap-6 lg:grid-cols-2"><Card className="border-white/10 bg-[#121212]" data-testid="settings-account-card"><CardHeader><CardTitle className="flex items-center gap-2 text-base font-normal"><KeyRound className="size-4 text-[#4d8aff]" />Account</CardTitle></CardHeader><CardContent className="space-y-4"><div><p className="text-[10px] uppercase tracking-[0.14em] text-zinc-600">Display name</p><p className="mt-1 text-sm text-zinc-200" data-testid="settings-display-name">{me.data?.display_name ?? "—"}</p></div><div><p className="text-[10px] uppercase tracking-[0.14em] text-zinc-600">Email</p><p className="mt-1 text-sm text-zinc-200" data-testid="settings-email">{me.data?.email ?? "—"}</p></div></CardContent></Card><Card className="border-white/10 bg-[#121212]" data-testid="settings-security-card"><CardHeader><CardTitle className="flex items-center gap-2 text-base font-normal"><LockKeyhole className="size-4 text-[#34c759]" />Security boundary</CardTitle></CardHeader><CardContent className="space-y-4 text-sm leading-6 text-zinc-500"><p>Statx sessions use an httpOnly cookie. Provider API keys and OAuth tokens never enter the browser or local storage.</p><div className="flex items-center gap-2 text-xs text-[#6ee7a1]"><ServerCog className="size-4" />Server-side provider routing enabled</div></CardContent></Card></div></div>;
}