import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTheme } from "next-themes";
import { Camera, Check, ImagePlus, Loader2, Moon, Palette, Sparkles, Sun, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Card } from "@/components/ui/card";
import { apiGet, apiPostForm } from "@/lib/api";
import type { UserPublic } from "@/lib/types";

const themes = [
  { id: "light", label: "Light", icon: Sun, preview: "from-white to-slate-100", text: "text-slate-700" },
  { id: "dark", label: "Dark", icon: Moon, preview: "from-slate-800 to-slate-950", text: "text-white" },
  { id: "system", label: "Automatic", icon: Sparkles, preview: "from-indigo-500 to-cyan-400", text: "text-white" },
] as const;

export default function Settings() {
  const client = useQueryClient();
  const [imageVersion, setImageVersion] = useState(Date.now());
  const me = useQuery({ queryKey: ["me"], queryFn: () => apiGet<UserPublic>("/auth/me") });
  const { theme, setTheme } = useTheme();
  const upload = useMutation({ mutationFn: ({ kind, file }: { kind: "avatar" | "banner"; file: File }) => { const form = new FormData(); form.append(kind, file); return apiPostForm<UserPublic>("/auth/profile/images", form); }, onSuccess: (user) => { client.setQueryData(["me"], user); setImageVersion(Date.now()); toast.success("Profile updated"); }, onError: (error: Error) => toast.error(error.message || "Image upload failed") });
  const name = me.data?.display_name ?? "StatNex learner";
  const imageUrl = (url?: string | null) => url ? `${url}${url.includes("?") ? "&" : "?"}client=${imageVersion}` : undefined;
  return <div className="space-y-7" data-testid="settings-page">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 via-blue-600 to-cyan-500 p-7 text-white shadow-xl shadow-indigo-200/40"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-2xl bg-white/15 text-white ring-1 ring-white/20"><Palette className="size-7" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-100">Make it yours</p><h1 className="mt-1 font-heading text-3xl font-semibold tracking-[-0.04em] text-white">Workspace settings</h1><p className="mt-2 text-sm text-blue-50">Add your own profile look and choose the theme that helps you focus.</p></div></div></section>
    <div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]">
      <Card className="overflow-hidden border-slate-200 bg-white shadow-sm" data-testid="settings-account-card"><div className="group relative h-36 bg-gradient-to-r from-indigo-600 via-blue-500 to-cyan-400">{me.data?.banner_url && <img src={imageUrl(me.data.banner_url)} alt="Profile banner" className="h-full w-full object-cover" data-testid="settings-banner-image" />}<label data-testid="settings-banner-upload-button" className="absolute right-4 top-4 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-slate-950/55 px-3 py-2 text-xs font-semibold text-white backdrop-blur hover:bg-slate-950/70"><ImagePlus className="size-4" />Change banner<input data-testid="settings-banner-input" type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={upload.isPending} onChange={(event) => { const file = event.target.files?.[0]; if (file) upload.mutate({ kind: "banner", file }); event.currentTarget.value = ""; }} /></label></div><div className="px-6 pb-6"><div className="relative -mt-10 size-20"><div className="grid size-20 place-items-center overflow-hidden rounded-2xl border-4 border-white bg-gradient-to-br from-indigo-600 to-blue-600 text-2xl font-bold text-white shadow-md">{me.data?.avatar_url ? <img src={imageUrl(me.data.avatar_url)} alt={name} className="h-full w-full object-cover" data-testid="settings-avatar-image" /> : name.slice(0, 1).toUpperCase()}</div><label data-testid="settings-avatar-upload-button" className="absolute -bottom-2 -right-2 grid size-8 cursor-pointer place-items-center rounded-full bg-indigo-600 text-white shadow-md hover:bg-indigo-700"><Camera className="size-4" /><input data-testid="settings-avatar-input" type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={upload.isPending} onChange={(event) => { const file = event.target.files?.[0]; if (file) upload.mutate({ kind: "avatar", file }); event.currentTarget.value = ""; }} /></label></div><h2 className="mt-5 font-heading text-xl font-semibold text-slate-900" data-testid="settings-display-name">{name}</h2><p className="mt-1 text-sm text-slate-500" data-testid="settings-email">{me.data?.email ?? ""}</p><div className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-xs font-medium text-emerald-700">{upload.isPending ? <Loader2 className="size-4 animate-spin" /> : <UserRound className="size-4" />}{upload.isPending ? "Uploading image…" : "Your learning workspace is ready"}</div></div></Card>
      <Card className="border-slate-200 bg-white p-6 shadow-sm" data-testid="settings-appearance-card"><div className="mb-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600">Appearance</p><h2 className="mt-1 font-heading text-xl font-semibold text-slate-900">Choose your theme</h2><p className="mt-1 text-sm text-slate-500">Your choice stays saved on this device.</p></div><div className="grid gap-3 sm:grid-cols-3">{themes.map(({ id, label, icon: Icon, preview, text }) => { const active = theme === id; return <button key={id} data-testid={`settings-theme-${id}`} onClick={() => setTheme(id)} className={`relative overflow-hidden rounded-2xl border p-2 text-left ${active ? "border-indigo-400 ring-4 ring-indigo-50" : "border-slate-200 hover:border-indigo-200"}`}><div className={`h-28 rounded-xl bg-gradient-to-br ${preview} p-4 ${text}`}><Icon className="size-5" /><p className="mt-8 text-sm font-semibold">{label}</p></div>{active && <span className="absolute right-4 top-4 grid size-6 place-items-center rounded-full bg-indigo-600 text-white"><Check className="size-3.5" /></span>}</button>; })}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-blue-50 p-4"><span className="block size-2 rounded-full bg-blue-500" /><p className="mt-3 text-xs font-semibold text-blue-800">Learn clearly</p></div><div className="rounded-xl bg-emerald-50 p-4"><span className="block size-2 rounded-full bg-emerald-500" /><p className="mt-3 text-xs font-semibold text-emerald-800">Practice actively</p></div><div className="rounded-xl bg-amber-50 p-4"><span className="block size-2 rounded-full bg-amber-500" /><p className="mt-3 text-xs font-semibold text-amber-800">Track progress</p></div></div></Card>
    </div>
  </div>;
}